CREATE TABLE scope1_emissions (
  id SERIAL PRIMARY KEY,
  year INTEGER,
  company_name TEXT,
  facility_name TEXT,
  equipment TEXT,
  type TEXT,
  category TEXT,
  description TEXT,
  fuel_type TEXT,
  specific_fuel TEXT,
  unit TEXT,
  total_consumption DECIMAL,
  converted_value DECIMAL,
  emission_factor DECIMAL,
  total_emission DECIMAL,
  jan DECIMAL,
  feb DECIMAL,
  mar DECIMAL,
  apr DECIMAL,
  may DECIMAL,
  jun DECIMAL,
  jul DECIMAL,
  aug DECIMAL,
  sep DECIMAL,
  oct DECIMAL,
  nov DECIMAL,
  dec DECIMAL
);